### ISSUE TITLE
Multiple Grouping Issues in Grid

### ISSUE THREAD

**Issue by Baidaly** [extnet/Ext.NET#264] opened 2013-06-04 23:36 UTC
http://forums.ext.net/showthread.php?25125
http://www.sencha.com/forum/showthread.php?264961

Thread posted by @vladsch (url moved below)

DUPs: 
http://forums.ext.net/showthread.php?25183
http://forums.ext.net/showthread.php?25442

**Comment by fabriciomurta** [comment] 2017-09-15 17:04
(moved from initial comment to ensure we're checking the right sencha thread against the issue's status)
Thread posted by @vladsch http://www.sencha.com/forum/showthread.php?265204

**Comment by fabriciomurta** [comment] 2017-09-15 17:05
**Update:** Sencha issue _EXTJS-10027_ allegedly fixed in ExtJS 4.2.2.1144 release.

**Comment by fabriciomurta** [comment] 2017-09-15 17:43
Couldn't reproduce the issue in current Ext.NET versions.

**Closed by fabriciomurta** 2017-09-15 17:43 UTC
Labels: 2.x, extjs-test-pending, fixed-in-latest-extjs, review, review-after-extjs-upgrade, sencha
