### ISSUE TITLE
Grid group header and its inner columns doesn't support flex

### ISSUE THREAD

**Issue by Baidaly** [extnet/Ext.NET#358] opened 2013-10-18 20:44 UTC
http://forums.ext.net/showthread.php?26901
http://forums.ext.net/showthread.php?38631
http://forums.ext.net/showthread.php?38731

http://www.sencha.com/forum/showthread.php?274106

**Comment by DaniilVeriga** [comment] 2015-08-26 18:26
That is a duplicate of:#89.

**Closed by DaniilVeriga** 2015-08-26 18:26 UTC
Labels: 2.x, 3.x, sencha
