### ISSUE TITLE
broken: ext-polarChart cannot be added in ext-panel's Items

### ISSUE THREAD

**Issue by fabriciomurta** [extnet/Ext.NET#1799] opened 2020-07-20 20:52 UTC
Found: Ext.NET 7.0.0-preview4_2020-07-18.

The `ext-polarChart` component is not being accepted within an `ext-panel`'s `items` block. The issue is as simple as:

```
<ext-panel />
  <items>
    <ext-polarChart />
  </items>
</ext-panel>
```

It was pointed by @AndreyChechel during our Monday meeting that just using `ext-container` instead of `ext-panel` works around the issue for `ext-polarChart`, and it applies to this component as well. So this issue is likely to be the same as #1798.

**Comment by geoffreymcgill** [comment] 2020-07-20 20:53
Duplicate of #1798, which will be fixed in `7.0.0-preview4`.

**Closed by geoffreymcgill** 2020-07-20 20:53 UTC
Labels: 7.x, asp-net-core, duplicate
