### ISSUE TITLE
GridPanel scrollbar resets after reload data

### ISSUE THREAD

**Issue by o3972680** [extnet/Ext.NET#1803] opened 2020-07-21 11:16 UTC
Version: ExtJS 5.0.1
After the grid table reloads data, the scroll bar will be reset. I have tried with preserveScrollOnRefresh in ViewConfig, it does not work. This bug may be fixed in the latest version, but our project is hard to upgrade.
How to solve this issue? We tried lots of methods, they are not work well.  Anyone else who can help on this? Thanks in advance!

**Comment by fabriciomurta** [comment] 2020-07-21 21:33
Hello @o3972680!

Thanks for taking your time to report the issue to us!

Unfortunately there's little we can do if you can't upgrade your project to the latest versions. As you expect, the issue is probably already fixed and what you could do is search through the fixed issues' history for something that may be exactly what you're facing; chances are you may find an override there that _may_ fix the issue in your version.

- [Ext.NET Issues search: scrollbar](https://github.com/extnet/Ext.NET/issues?q=is%3Aissue+scrollbar)

If you really meant **Ext JS 5.0.1** and not **Ext.NET 5.0.1** though, this would be something equivalent to early Ext.NET 3.x releases, which are now end-of-life and you should really consider upgrading if you mean to stay up to speed with modern browsers and technologies. If you meant **Ext.NET 5.0.1** you shouldn't have much trouble upgrading, really.

Another option for you is to isolate the issue in a test case. In case it is reproducible in latest Ext.NET, then chances is we may just find a solution that also works for you in your older version -- no guarantees, though.

In case you are up for the test case, post a it, with a step-thru to reproduce the issue, so we can replay it and see the scroll reset happening. Telling us exactly which web browser and version you are using should also be helpful!

A good starting point for single-file test cases would be to base off one of our examples from the Examples Explorer. A good one for grid to start with would be the [GridPanel > ArrayGrid > Simple](https://examples5.ext.net/#/GridPanel/ArrayGrid/Simple/) but you may want to browse a litthe the available examples to see if there's something even closer to your scenario so you can expand from that.

We'll be closing this issue for now but in case you can fill us in with more information we'd be more than eager to reopen and handle it!

Hope this helps!

**Closed by fabriciomurta** 2020-07-21 21:33 UTC
