### ISSUE TITLE
TextField with RightButtons and LeftButtons can raise a JavaScript error in some scenario

### ISSUE THREAD

**Issue by ismailkocacan** [extnet/Ext.NET#873] opened 2015-08-19 08:28 UTC
I'm testing that release https://www.nuget.org/packages/Ext.NET/3.2.0

I'm testing that sample http://mvc.ext.net/GridPanel_ComponentColumn/Editor/ working well.

I have added "Button-Edit" component column like that.

<pre><code class='language-cs'>
@model System.Collections.IEnumerable

@{

    var X = Html.X();
}

@(Html.X().GridPanel()
        .Title("ComponentColumn Editor")
        .Width(800)
        .Height(400)
        .Frame(true)
        .Border(true)
        .Store(Html.X().Store()
            .Model(Html.X().Model()
                .Fields(
                    new ModelField("IntField", ModelFieldType.Int),
                    new ModelField("ComboField", ModelFieldType.Int),
                    new ModelField("TextField", ModelFieldType.String),
                    new ModelField("DateField", ModelFieldType.Date),
                    new ModelField("FloatField", ModelFieldType.Float)
                )
            )
            .DataSource(Model)
        )
        .ColumnModel(
            Html.X().ComponentColumn()
                .Editor(true)
                .DataIndex("IntField")
                .Flex(1)
                .Text("Integer")
                .Component(Html.X().NumberField()),

            Html.X().ComponentColumn()
                .Editor(true)
                .DataIndex("ComboField")
                .Flex(1)
                .Text("ComboBox")
                .Component(Html.X().ComboBox()
                    .Items(
                        new ListItem("Item 1", 1),
                        new ListItem("Item 2", 2),
                        new ListItem("Item 3", 3),
                        new ListItem("Item 4", 4),
                        new ListItem("Item 5", 5),
                        new ListItem("Item 6", 6),
                        new ListItem("Item 7", 7),
                        new ListItem("Item 8", 8),
                        new ListItem("Item 9", 9)
                    )
                ),

            Html.X().ComponentColumn()
                .Editor(true)
                .DataIndex("TextField")
                .Flex(1)
                .Text("Text")
                .Component(Html.X().TextField()),

            Html.X().ComponentColumn()
                .Editor(true)
                .DataIndex("DateField")
                .Flex(1)
                .Text("Date")
                .Component(Html.X().DateField()),

           Html.X().ComponentColumn()
                .Editor(true)
                .DataIndex("TextField")
                .Flex(1)
                .Text("Button")
                .Component
                (
                 Html.X().Button().Text("Hesapla").Icon(Icon.Accept)
                 .DirectEvents
                 (de =>
                          {
                              de.Click.Url = Url.Action("Save");
                              de.Click.ExtraParams.Add(new Parameter("param1", "Hello1!", ParameterMode.Value));
                          }
                 )

                ),

           Html.X().ComponentColumn()
                .Editor(true)
                .Flex(1)
                .DataIndex("TextField")
                .Text("Button-Edit")
                .Component
                (
                    Html.X().TextField()
                   .RightButtons(X.Button().Icon(Icon.ApplicationViewList))
                   .RightButtonsShowMode(ButtonsShowMode.MouseOverOrFocus)
                ),

            Html.X().ComponentColumn()
                .Editor(true)
                .DataIndex("FloatField")
                .Flex(1)
                .Text("FloatField")
                .Component
                (
                   Html.X().NumberField()
                   .DecimalPrecision(2)
                   .Editable(false)
                   .EmptyNumber(0)
                   .AllowDecimals(true)
                   .DecimalSeparator(".")
                )
        )
)
</code></pre>

Controller 

<pre><code class='language-cs'>
  public class GridPanelComponentController : Controller
    {
        //
        // GET: /GridPanelComponent/

        public static IEnumerable GetData()
        {
            DateTime now = DateTime.Now;

            return new object[]
                {
                    new object[] { 1, 1, "Text 1", DateTime.Now.Date,20.1 },
                    new object[] { 2, 2, "Text 2", DateTime.Now.Date,20.20 },
                    new object[] { 3, 3, "Text 3", DateTime.Now.Date,20.354 },
                    new object[] { 4, 4, "Text 4", DateTime.Now.Date,20.42 },
                    new object[] { 5, 5, "Text 5", DateTime.Now.Date,20.53 },
                    new object[] { 6, 6, "Text 6", DateTime.Now.Date,20.65 },
                    new object[] { 7, 7, "Text 7", DateTime.Now.Date,20.750 },
                    new object[] { 8, 8, "Text 8", DateTime.Now.Date,20.88 },
                    new object[] { 9, 9, "Text 9", DateTime.Now.Date,20.99 }
                };
        }

        public Ext.Net.MVC.PartialViewResult Form1(string containerId)
        {
            return new Ext.Net.MVC.PartialViewResult
            {
                Model = GetData(),
                RenderMode = RenderMode.AddTo,
                ContainerId = containerId,
                WrapByScriptTag = false 
            };
        }

        public ActionResult Save(String param1)
        {
            X.Msg.Alert("Serialized", param1).Show();
            return this.Direct();
        }
    }
</code></pre>

Result View
![ScreenShot](https://lh3.googleusercontent.com/53LoZSggHSm1oF8ERO776jhmPfTZe7zppGGO9JBIAPU=w807-h406-no)

When I added "Button-Edit" Component column.
- Doesn't firing "Hesapla" button.
- "Button-Edit" component column another rows not rendering.
- ComboBox not opening.

Can be a bug ?

Thanks

**Comment by DaniilVeriga** [comment] 2015-08-19 13:41
There is a JavaScript occurred because of `.RightButtons(...)`. Please remove it for now and everything should start working. Meanwhile, I am investigating a possible fix. Thank you for the report!

**Comment by ismailkocacan** [comment] 2015-08-19 13:56
When I remove "button-edit" component column working well.I know. 
thanks for reply.

**Comment by DaniilVeriga** [comment] 2015-08-19 14:01
You can keep the "button-edit" ComponentColumn, but without RightButtons.

**Comment by ismailkocacan** [comment] 2015-08-19 14:04
hımm
Did you implement RightButtons method body ?

**Comment by DaniilVeriga** [comment] 2015-08-19 14:12
Sorry, I don't understand. Please elaborate.

**Comment by ismailkocacan** [comment] 2015-08-19 14:17
I did think source of problem that RightButtons methods inside.

**Comment by DaniilVeriga** [comment] 2015-08-19 14:39
Fixed in the revision 6532 (trunk). The fix goes to 3.2.1.

**Closed by DaniilVeriga** 2015-08-19 14:39 UTC
Labels: 3.x

**Comment by ismailkocacan** [comment] 2015-08-19 14:42
thanks for solution Danill :)

**Comment by ismailkocacan** [comment] 2015-08-27 17:40
Hi again Daniil
I have tested "Button-Edit" column with ext.net 3.2.1
I'm used big data (3164210 million row) .
if you want to steps to reproduce then I can give you specifiy more detail.

![ScreenShot](https://lh3.googleusercontent.com/LwjZj2Hwbb751VNC3X8jp9N_9gDDghIHXO2KT63gY24=w712-h509-no)

**Comment by DaniilVeriga** [comment] 2015-08-28 08:49
Please clarify is it only reproducible with RightButtons/LeftButtons?

**Comment by ismailkocacan** [comment] 2015-08-28 10:17
I have tried LeftButtons and RightButtons.
![ScreenShot](https://lh3.googleusercontent.com/gyt9ldR3Y7mdaW_jRpzxjgNU9HzPLmKzHgLz5hoeYh8=w908-h509-no)

**Comment by DaniilVeriga** [comment] 2015-08-28 11:03
I am rather asking have you tried **without** RightButtons and LeftButtons at all?

**Comment by ismailkocacan** [comment] 2015-08-28 11:36
Yes.I also have tried **without** LeftButtons and RightButtons.

**Comment by DaniilVeriga** [comment] 2015-08-28 12:27
So, it is another issue. I mean it is not related to LeftButtons and RightButtons and that contradicts the Issue title. Each issue is meant to cover the only issue. It is the only way to keep things clear and organized. I am pretty sure you are facing the same or very similar issue to #800. I posted a comment there.

**Comment by ismailkocacan** [comment] 2015-08-28 12:47
You're right.
When I tested after set BufferedRenderer(false).it worked well
Thanks for reply Daniil.
