### ISSUE TITLE
Chart Axis length and width doesn't work

### ISSUE THREAD

**Issue by DaniilVeriga** [extnet/Ext.NET#90] opened 2012-12-26 17:14 UTC
http://forums.ext.net/showthread.php?22755

http://www.sencha.com/forum/showthread.php?252356

**Update:** Issue still open after ExtJS 6.0.1 release.

**Comment by fabriciomurta** [comment] 2016-04-23 21:05
**Update:** Issue still open after ExtJS 6.0.2 release.

**Comment by fabriciomurta** [comment] 2017-07-25 19:55
**Update:** Issue is allegedly irreproducible by the time ExtJS 6.5.0 was released.

**Comment by fabriciomurta** [comment] 2017-09-15 18:09
**Update:** Issue is allegedly irreproducible by the time ExtJS 6.5.1 was released. Sencha allegation: unable to reproduce the issue.

**Comment by fabriciomurta** [comment] 2017-09-15 21:58
There's no `length` nor `width` settings to [Ext.chart.axis.Category](http://docs.sencha.com/extjs/6.5.1/classic/Ext.chart.axis.Category.html)

It sounds like ExtJS just does not support axis "zero point" mangling.

(actually, `length` exists, is private but its documentation does not suggest it could be used to move the zero point of the scale around).

**Comment by fabriciomurta** [comment] 2017-09-15 22:00
Actually this issue does not correspond to the Ext.NET thread. This should be closed as the properties are not exported by ExtJS (as public properties) nor meant to be supported at all.

**Closed by fabriciomurta** 2017-09-15 22:00 UTC
Labels: 2.x, 3.x, 4.x, defect, review-after-extjs-upgrade, sencha, sencha-disclaim
