### ISSUE TITLE
Ext.Net.TagField issues on auto-completion and creating custom tags

### ISSUE THREAD

**Issue by fabriciomurta** [extnet/Ext.NET#1333] opened 2016-05-17 19:55 UTC
Ext.NET's tag field component is not the same as ExtJS. The current Ext.NET implementation had some recent fixes in #1323 and #1324 but still has issues regarding auto-completion according to this forum thread: [Incorrect operation of the TagField](http://forums.ext.net/showthread.php?61114).

According to the user report, Sencha's version does not have this problem.

**Comment by fabriciomurta** [comment] 2016-05-17 20:10
Seems the issues mentioned above fixes only for 4.x.

**Comment by DaniilVeriga** [comment] 2016-05-19 13:34
> Ext.NET's tag field component is not the same as ExtJS. 

Yes, true. The component appeared in Ext.NET before it appeared in ExtJS. Ext.NET TagField has some functionality over ExtJS one and our TagField has been left.

> According to the user report, Sencha's version does not have this problem.

Yes,

#1324 has been now fixed in v3 as well. The fix is available in the sources right away. It will be included into the next v3 public release if ever.

#1323 is not reproducible with v3, i.e. it doesn't trigger any JavaScript error. But yes, TagField's `TypeAhead="true"` functionality appears to be broken in v3. It correctly populates the remainder of the text, but it doesn't autoselect it. It is because of `.selectText()` method which is defined in TextField and doesn't work for TagField. Created a dedicated issue #1334 and fixed already.

Now I am investigating the issue stated in this [forum post](http://forums.ext.net/showthread.php?61114&p=278744&viewfull=1#post278744).

**Comment by DaniilVeriga** [comment] 2016-05-20 12:26
I am closing this issue as it looks like all issues have been addressed.

**Closed by DaniilVeriga** 2016-05-20 12:26 UTC
Labels: 3.x, defect
