### ISSUE TITLE
TabCloseMenu is broken

### ISSUE THREAD

**Issue by DaniilVeriga** [extnet/Ext.NET#301] opened 2013-07-16 08:34 UTC
A sub-issue of #294.

Fixed in revision 5256. Review after Sencha fixes.

**Comment by fabriciomurta** [comment] 2017-09-15 16:37
The original issue (http://www.sencha.com/forum/showthread.php?264507) is marked as duplicate of EXTJSIV-9861, but there's no link for any public forums thread related to this issue at all. Removing the link from original issue.

**Comment by fabriciomurta** [comment] 2017-09-15 16:42
Reviewing the issue at Ext.NET 6.5.1, TabCloseMenu is 100% pulled from ExtJS and the issues in the Sencha thread report are no longer reproducible. So there's no overrides left in Ext.NET that addresses the issue anymore and this can be closed.

**Closed by fabriciomurta** 2017-09-15 16:42 UTC
Labels: 2.x, defect, extjs-test-pending, review, review-after-extjs-upgrade, sencha
