### ISSUE TITLE
实例GridFilters Remote有问题

### ISSUE THREAD

**Issue by zhoujianxiong** [extnet/Ext.NET#1319] opened 2016-04-29 09:11 UTC
在实例GridPanel=>Plugins=>GridFilters Remote中使用Size的Filters会出现无限刷新的问题

**Comment by fabriciomurta** [comment] 2016-04-29 13:23
Hello! Thanks for the report! Can you review your bug report in English please?

Google translate suggests this text:
_"Examples GridPanel => Plugins => GridFilters Remote use Size will appear in the Filters Unlimited refresh problem"_

Okay, I seem to be able to reproduce something here. Once a filter entry is chosen in the `Size` column, the grid gets stuck on a loop updating over and over.

**Comment by fabriciomurta** [comment] 2016-04-29 13:30
We have just tested this on our upcoming 4.1.0 examples explorer and the issue is no longer reproducible once we merged Ext.NET with ExtJS 6.0.2.

**Closed** 2016-04-29 13:32 UTC
Labels: 4.x, defect, examples

**Comment by zhoujianxiong** [comment] 2016-04-29 15:40
Thank you for your reply
